#!/bin/bash
#
# Convert bank csv exports to json for ledger

unset -v DIRECTORY

usage() {
  echo "$0 -d <directory containing csv files>" >&2
}

parse_args() {
  while getopts "d:" arg; do
    case $arg in
      d) 
        DIRECTORY="$OPTARG"
        readonly DIRECTORY
        ;;
    esac
  done

  if [[ -z "$DIRECTORY" ]]; then
    echo "No directory specified." >&2
    usage
    exit 1
  fi
}

format_bank_statements() {
  for formatting_script in $(ls ./utils/awk/from-*); do
    apply_format "${formatting_script}"
  done;
}

apply_format() {
  local formatting_script
  local bank_name
  local account_name
  formatting_script=$1
  bank_name="$(basename -s .awk "${formatting_script/from-/}")"
  for filepath in "${DIRECTORY}"/*"${bank_name}"*.csv; do
    if [[ -f "${filepath}" ]]; then
      account_name="$(basename -s .csv "${filepath//[-_]/:}")"
      "$formatting_script" -v account="$account_name" "${filepath}"
    fi
  done;
}

main() {
  parse_args "$@"
  (format_bank_statements) | sort | ./utils/awk/to-json.awk
}

main "$@"
