#!/bin/bash
#
# Convert bank csv exports to json for ledger

load_bank_statements() {
  local directory=$1
  for bank_name in 'hsbc' 'monzo'; do
    process_bank_statements $bank_name $directory
  done;
}

process_bank_statements() {
  local bank_name=$1
  local directory=$2
  for filename in $directory/*$bank_name*.csv; do
    [[ -f $filename ]] && ./utils/awk/from-$bank_name.awk \
      -v account=$(filename_to_accountname $filename) \
      $filename
  done;
}

filename_to_accountname() {
  local bank_name=$1
  basename $bank_name | sed -E 's/-|_/:/g; s/\.\///; s/.csv//'
}

(load_bank_statements $1) | sort | ./utils/awk/to-json.awk
