#!/bin/bash
#
# Convert bank csv exports to json for ledger

unset -v DIRECTORY

parse_args() {
  while getopts "d:" arg; do
    case $arg in
      d) 
        DIRECTORY="$OPTARG"
        readonly DIRECTORY
        ;;
    esac
  done
}

load_bank_statements() {
  for bank_name in 'hsbc' 'monzo' 'tsb'; do
    process_bank_statements "${bank_name}"
  done;
}

process_bank_statements() {
  local bank_name=$1
  for filepath in "${DIRECTORY}"/*"${bank_name}"*.csv; do
    if [[ -f "${filepath}" ]]; then
      local account_name
      account_name="$(basename -s .csv "${filepath//[-_]/:}")"
      ./utils/awk/from-"${bank_name}".awk \
        -v account="$account_name" \
        "${filepath}"
    fi
  done;
}

main() {
  parse_args "$@"
  (load_bank_statements) | sort | ./utils/awk/to-json.awk
}

main "$@"
